arb-dir: l10n
output-dir: lib/l10n
output-class: AppLocalizations
nullable-getter: false
use-escaping: true
template-arb-file: app_en.arb
preferred-supported-locales: [en, en_US, en_UK, de]
synthetic-package: false
